### ISSUE TITLE
Create Player Class

### ISSUE THREAD

**Issue by cgacord** [murphy360/discord-bot-everything#37]
Player Class will contain:
 - Player Data (User ID, Username, # of Wins, Win_streak, #incorrect_answers, #correct_answers)
 - method to calculate win percentage
 - method to calculate correct answer percentage

<img width="1070" alt="Screen Shot 2021-04-18 at 10 34 48 PM" src="https://user-images.githubusercontent.com/15983047/115173940-4b12e480-a096-11eb-9d57-5422fa867999.png">

**Comment by RonConescu** [comment]
This diagram is awesome! Where and how did you create it?  Is it stored in the project?

**Comment by cgacord** [comment]
Created it in Powerpoint. We have a oneDrive that holds the actual [power point file](https://1drv.ms/p/s!AoKM5qWiuXllhd8pM7YnOrCY4pmVmg?e=aXfLNU).

Corey and I created these when we were discussing how to implement the databases. I was very object oriented at the time and he was database oriented and we were talking past each other, so there is another slide that talks about the database construct we will use.

**Comment by murphy360** [comment]
complete
